
version: 2
updates:
  # GitHub Actions için bağımlılık güncellemelerini yönet
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # npm paketleri için bağımlılık güncellemelerini yönet
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
