// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xppszoujtypudpubfeym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcHN6b3VqdHlwdWRwdWJmZXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDg0NTIsImV4cCI6MjA2MzMyNDQ1Mn0.WxdwYELkyJTML4MJgMnWdN90Flg0rp2NWRYc3HXdFL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);